services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    image: robertjmarlow/fia-swear-bot-bot
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_started
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    image: robertjmarlow/fia-swear-bot-db
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./db:/usr/local/etc/redis/db
